version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/build/
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: scripts/applicationStop.sh
      timeout: 180
    - location: scripts/applicationStart.sh
      timeout: 180
