version: 0.2

phases:
  install:
    commands:
      - echo Installing babel-cli
      - npm install -g babel-cli
  pre_build:
    commands:
      - echo Installing source NPM dependencies....
      - npm install
  build:
    commands:
      - echo Build resume-react-express on $(date +%Y-%m-%d_%H%M)
      - npm run build
  post_build:
    commands:
      - echo Build Completed on $(date +%Y-%m-%d_%H%M)
artifacts:
  files:
    - 'build/**/*'
    - 'scripts/*'
    - 'public/**/*'
    - 'server/**/*'
    - 'src/**/*'
    - 'node_modules/**/*'
    - 'package.json'
    - 'appspec.yml'
  name: resume-react-express_$(date +%Y-%m-%d_%H%M)

cache:
  paths:
    - '/node_modules/**/*'
