version: 0.2

phases:
  install:
    commands:
      - echo Installing babel-cli
      - npm install -g babel-cli
  pre_build:
    commands:
      - echo Installing source NPM dependencies....
      - npm install
  build:
    commands:
      - echo Build resume-react-express on `date`
      - npm run build
  post_build:
    commands:
      - echo Build Completed on `date`
artifacts:
  files:
    - /

cache:
  paths:
    - '/node_modules/**/*'
